---

- hosts: k3s
  gather_facts: true
  become: true
  roles:
    - role: prereq
    - role: download
    # - role: raspberrypi

- hosts: k3s_control
  become: true
  roles:
    - role: k3s/master

- hosts: k3s_nodes
  become: true
  roles:
    - role: k3s/node

- hosts: k3s_control
  become: true
  roles:
    - role: k3s/post
